version: '3.8'  # 使用 Docker Compose 版本 3.8

services:
  webapp:  # 服务名称，可以根据你的应用程序进行更改
    image: ai-router:latest  # 使用的镜像和标签
    ports:
      - "8080:8080"  # 将容器的 8080 端口映射到宿主机的 8080 端口
    volumes:
      - "/root/data/ai-router/conf:/app/config"  # 将宿主机的配置目录映射到容器的 /app/config
    environment:
      - APP_ENV=production  # 可以指定环境变量
    restart: unless-stopped  # 除非手动停止，否则总是重新启动服务
